module.exports = {
  packages: [
    "getting-started",
    {
      type: "category",
      label: "Components",
      items: [
        "components/UI",
        "components/styling",
        "components/animation",
        "components/libraries",
        "components/frameworks",
      ],
    },
    "deepLinking",
    "buildAndDevelopment",
    "extension",
    "forms",
    "integrations",
    "media",
    "navigation",
    "textAndRichContent",
    "otherPlatforms",
    "monetization",
    "seeds",
    "utilsAndInfra",
    "system",
    "utilities",
    "web",
    "backend",
    "geolocation",
    "storage",
    "internationalization",
    "analytics",
    "openSourceApps",
    "tutorials",
    "trainingAndTutorials",
    "blogs",
    "books",
    "talks",
    "newsletters",
  ],
};
