module.exports = {
  packages: [
    {
      type: "category",
      label: "Category",
      items: [
        {
          type: "category",
          label: "Components",
          items: [
            "components/UI",
            "components/navigation",
            "components/deepLinking",
            "components/analytics",
            "components/textAndRichContent",
            "components/utilsAndInfra",
            "components/forms",
            "components/geolocation",
            "components/internationalization",
            "components/buildAndDevelopment",
            "components/styling",
            "components/system",
            "components/web",
            "components/media",
            "components/storage",
            "components/backend",
            "components/integrations",
            "components/monetization",
            "components/animation",
            "components/extension",
            "components/otherPlatforms",
            "components/utilities",
            "components/seeds",
            "components/libraries",
            "components/frameworks",
          ],
        },
        "getting-started",
        "usage",
        "openSourceApps",
        "tutorials",
        "trainingAndTutorials",
        "blogs",
        "books",
        "talks",
        "newsletters",
        "props",
        "methods",
        "hooks",
        "scrollables",
        {
          type: "category",
          label: "Guides",
          items: [
            "guides/custom-handle",
            "guides/custom-backdrop",
            "guides/custom-background",
            "guides/custom-footer",
            "guides/detach-modal",
            "guides/keyboard-handling",
            "guides/pull-to-refresh",
            "guides/adding-shadow",
            "guides/react-navigation-integration",
          ],
        },
        "troubleshooting",
        "faq",
      ],
    },
    /* {
      type: "category",
      label: "Bottom Sheet Modal",
      items: [
        "modal/getting-started",
        "modal/usage",
        "modal/props",
        "modal/methods",
        "modal/hooks",
      ],
    } */
    ,
  ],
};
